spring.application.name=challenge
spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
spring.datasource.username=rm97510
spring.datasource.password=011003
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
server.servlet.context-path=/stylishpro
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.hibernate.SQL=DEBUG
#spring.ai.provider=openai
#spring.ai.openai.api-key=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
spring.ai.openai.api-key=BF5ufahnqtZclNZSItzCc0CrvG54vwZUjVvNA9JoFcr9Fp8RVCEOJQQJ99AKACYeBjFXJ3w3AAABACOGhTEq
spring.ai.azure.openai.api-key=BF5ufahnqtZclNZSItzCc0CrvG54vwZUjVvNA9JoFcr9Fp8RVCEOJQQJ99AKACYeBjFXJ3w3AAABACOGhTEq
spring.ai.azure.openai.deployment-name=modelochallenge
spring.ai.azure.openai.endpoint=https://rm975-m328aai6-eastus.openai.azure.com/openai/deployments/modelochallenge/images/generations

springdoc.show-actuator=true
management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#management.endpoint.health.probes.enabled=true
management.server.port=8081
spring.profiles.active=dev

